model = "gpt-5-codex"
model_reasoning_effort = "medium"
[projects."~/box"]
trust_level = "trusted"
auto_update = false

[features]
approve_all = true
web_search_request = true
plan_tool = true
unified_exec = true
streamable_shell = true
