"ui.background" = { bg = "#000000" }
"ui.text" = "#ffffff"
"ui.text.focus" = "#ffffff"
"ui.selection" = { bg = "#353535" }
"ui.cursorline" = { bg = "#0d0d0d" }
"ui.cursor" = { fg = "#000000", bg = "#ffffff" }
"ui.cursor.match" = { bg = "#353535" }
"ui.linenr" = "#868686"
"ui.linenr.selected" = "#ffffff"
"ui.statusline" = { fg = "#ffffff", bg = "#0d0d0d" }
"ui.statusline.inactive" = { fg = "#868686", bg = "#000000" }
"ui.popup" = { fg = "#ffffff", bg = "#0d0d0d" }
"ui.window" = { fg = "#868686" }
"ui.help" = { fg = "#ffffff", bg = "#0d0d0d" }
"ui.menu" = { fg = "#ffffff", bg = "#0d0d0d" }
"ui.menu.selected" = { fg = "#ffffff", bg = "#353535" }

"comment" = "#7f848e"
"string" = "#ffd866"
"constant" = "#00b7ff"
"constant.numeric" = "#00b7ff"
"constant.builtin" = "#00b7ff"
"variable" = "#ffffff"
"variable.parameter" = "#ffffff"
"variable.builtin" = "#00ffcf"
"type" = "#60fa67"
"function" = "#7c83fd"
"function.builtin" = "#7c83fd"
"keyword" = "#ff6b6b"
"keyword.control" = "#ff6b6b"
"operator" = "#ff77ff"
"tag" = "#00ffcf"
"attribute" = "#60fa67"
"namespace" = "#60fa67"
"special" = "#ff77ff"

"diagnostic.error" = { underline = { color = "#ff6b6b", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#ffd866", style = "curl" } }
"diagnostic.info" = { underline = { color = "#7c83fd", style = "curl" } }
"diagnostic.hint" = { underline = { color = "#868686", style = "curl" } }

